version: "3.3"
services:
 php-apache:
   image: "php:apache"
   restart: always
   ports:
   - 8080:80
   volumes:
     - ./:/var/www/html
   depends_on:
     - MariaDb
 MariaDb:
   image: "mariadb:latest"
   restart: always
   environment:
     MYSQL_ROOT_PASSWORD: example
     MYSQL_USER: sinstranger
     MYSQL_PASSWORD: example
   volumes:
     - "./mysql/:/var/lib/mysql/"
 Adminer:
   image: "adminer:latest"
   restart: always
   environment:
     ADMINER_DESIGN: pappu687
   ports:
     - 8081:8080
   links:
     - "MariaDb:db"
   depends_on:
     - MariaDb